# Generated by Django 4.0.4 on 2022-05-29 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('question', models.CharField(max_length=255)),
                ('placehold', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('short_answer', 'Short Answer'), ('multiple_choice', 'Multiple Choice'), ('numeric_answer', 'Numuric Answer'), ('dropdown', 'Dropdown'), ('date', 'Date'), ('idno', 'Id Card Number'), ('file', 'File')], default='', max_length=20)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('idcard', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('birthday', models.DateField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phonenumber', models.CharField(default='xxxxxxxxxx', max_length=20, unique=True)),
                ('auth_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('input_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_forms.input')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(max_length=255)),
                ('value_integer', models.IntegerField()),
                ('value_date', models.DateField()),
                ('value_file', models.FileField(upload_to='')),
                ('input_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_forms.input')),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_forms.respondent')),
            ],
        ),
    ]
